### ISSUE TITLE
Meta: maintenance tasks for next release

### ISSUE THREAD

**Issue by usmonster** [taitems/jQuery.Gantt#162]
Some stuff to do for v1.2.0:
- [ ] **Reevaluate this list!** Move some tasks to other tickets/releases, possibly use "Projects"?
- [x] merge `develop` branch into `master`
- [x] delete `develop` branch
- [ ] merge `master` branch into `gh-pages`
- [ ] Update README:
  - [ ] Update the list of features to be more comprehensive
  - [ ] Maybe add comparison to other Gantt implementations out there?
  - [ ] Merge in updated CONTRIBUTORS file content into its own section (can add back [CONTRIBUTING](https://blog.github.com/2012-09-17-contributing-guidelines/) file with details later only if needed)
  - [ ] Remove CONTRIBUTORS file
- [ ] Some more CSS cleanup:
  - [ ] replace images with data URIs in CSS (then remove img directory)
  - [ ] remove references to `gantt` & `gantt2` classes (update demo accordingly)
  - [x] switch to border-box box model (#102)
- [ ] replace jquery.cookie support with [JS Cookie](/js-cookie/js-cookie) support
- [ ] adopt AMD or ESM pattern
- [ ] minify js (note in README that pull requests should not contain changes to minified file(s))
- [ ] Add appropriate dotfiles:
  - [ ] add .eslintrc file
  - [ ] add .editorconfig file
  - [ ] add .gitattributes file
- [x] Add [package.json](https://docs.npmjs.com/getting-started/creating-node-modules) for npm (remember to add `jquery-plugin` and `ecosystem:jquery` keywords - [ref](https://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick))
- [ ] add tag & release notes (#161)
- [x] Register on [npm registry](https://docs.npmjs.com/getting-started/publishing-npm-packages)
- [ ] Update reference on [cdnjs](https://github.com/cdnjs/cdnjs) (cdnjs/cdnjs#6099, cdnjs/cdnjs#7005)

**Comment by taitems** [comment]
How do you feel about using using a specific CI tool, or alternatively github actions to achieve some of these tasks?

At ACG we're using buildkite for CI/CD, lerna to publish packages etc. I'm very green on github actions.

**Comment by usmonster** [comment]
I think most of the tasks in this particular issue are one-offs that can only (or make more sense to) be done manually, but I'd definitely be up to use GitHub Actions to tag & publish new versions going forward!
